package interf;

import itpmproject.DBconnect;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author priya
 */
public final class displaySubjectdetails extends javax.swing.JFrame {
    
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    /**
     * Creates new form displaySubjectdetails
     */
    public displaySubjectdetails() {
        initComponents();
        
        //connect to the DB
        con = DBconnect.connect();
        
        //load table
        tableload();
    }
    
    
     public void tableload()
    {
        try
        {
            String sql = "SELECT id,offeredyr,offeredsem,subname,subcode,lecturehrs,labhrs,tutehrs,evahrs FROM sub_details";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            
            displaysubjectdetails.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch (SQLException e)
        {
        
        }
    
     
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        displaysubjectdetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tutebox = new javax.swing.JLabel();
        labbox = new javax.swing.JLabel();
        evaluationbox = new javax.swing.JLabel();
        lhoursbox = new javax.swing.JSpinner();
        thoursbox = new javax.swing.JSpinner();
        labhoursbox = new javax.swing.JSpinner();
        ehoursbox = new javax.swing.JSpinner();
        offeredyearbox = new javax.swing.JComboBox<>();
        snamebox = new javax.swing.JTextField();
        scodebox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        semesterbox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        idbox = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        displaysubjectdetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "SUBJECT NAME", "SUBJECT CODE", "OFFERED YEAR", "OFFERED SEMESTER"
            }
        ));
        displaysubjectdetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displaysubjectdetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(displaysubjectdetails);

        jLabel1.setText("      DISPLAY SUBJECT DETAILS");

        jLabel2.setText("Offered year                 :");

        jLabel3.setText("Offered semester         :");

        jLabel4.setText("Subject name               :");

        jLabel5.setText("Subject code                : ");

        jLabel6.setText("Number of Lecturer hours       :");

        tutebox.setText("Number of Tutorial hours        :");

        labbox.setText("Number of Lab hours               :");

        evaluationbox.setText("Number of Evaluation hours    :");

        offeredyearbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Offered year", "1", "2", "3", "4" }));

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("DELETE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("CLEAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("NEXT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        semesterbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select offered semester", "1", "2" }));

        jLabel7.setText("ID     :");

        idbox.setText("ID");

        jButton5.setText("ADD NEW DATA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(snamebox)
                                    .addComponent(offeredyearbox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(semesterbox, javax.swing.GroupLayout.Alignment.LEADING, 0, 189, Short.MAX_VALUE)
                                    .addComponent(scodebox))
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(tutebox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labbox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(evaluationbox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ehoursbox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labhoursbox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(thoursbox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lhoursbox, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(idbox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(147, 147, 147))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 875, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(273, 273, 273)
                                .addComponent(jButton1)
                                .addGap(125, 125, 125)
                                .addComponent(jButton2)
                                .addGap(102, 102, 102)
                                .addComponent(jButton3)))
                        .addContainerGap(91, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(lhoursbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(offeredyearbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tutebox)
                            .addComponent(thoursbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(semesterbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(labbox)
                            .addComponent(labhoursbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(snamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(evaluationbox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ehoursbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scodebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton6))
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(idbox))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        insertsession i1 = new insertsession();
        i1.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //update button
        
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to update!!");
        
        if(x ==0)
        {
             try
            {
            String id = idbox.getText();
            String year = offeredyearbox.getSelectedItem().toString();
            String semester = semesterbox.getSelectedItem().toString();
            String subjectname = snamebox.getText();
            String subjectcode = scodebox.getText();
            String lhours = lhoursbox.getValue().toString();
            String labhours  = labhoursbox.getValue().toString();
            String thours  = thoursbox.getValue().toString();
            String ehours  = ehoursbox.getValue().toString();
            
            
           
            String sql = "UPDATE sub_details SET offeredyr = '"+ year +"',offeredsem = '"+ semester +"',subname = '"+ subjectname +"',subcode = '"+ subjectcode +"', lecturehrs = '"+ lhours +"', labhrs = '"+ labhours +"',tutehrs = '"+ thours +"',evahrs = '"+ ehours +"' where id = '"+ id +"' ";
            
           
                pst = con.prepareStatement(sql);
                pst.execute();
                
                JOptionPane.showMessageDialog(null,"Data Successfully Updated!");
                
                //load table
                
                tableload();
            
            }catch (HeadlessException | SQLException e){
                
                JOptionPane.showMessageDialog(this, e.getMessage());
                
            }
        
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //delete button
        
        
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to delete this data!");
        if(x==0)
       {
           try
           {
           
           String id = idbox.getText();
           String sql = "DELETE from sub_details where id = '"+ id +"' ";
           
           
               pst = con.prepareStatement(sql);
               pst.execute();
               
               JOptionPane.showMessageDialog(null,"Data Successfully Deleted!");
               

                //load table
                
                tableload();
               
           
           }
           catch (HeadlessException | SQLException e){
               
               JOptionPane.showMessageDialog(this, e.getMessage());
           
           }
       
       }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void displaysubjectdetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displaysubjectdetailsMouseClicked
        // TODO add your handling code here:
        
        //for do the delete and update part
        int r = displaysubjectdetails.getSelectedRow();
        
        String id = displaysubjectdetails.getValueAt(r, 0).toString();
        String year = displaysubjectdetails.getValueAt(r, 1).toString();
        String semester = displaysubjectdetails.getValueAt(r, 2).toString();
        String subjectname = displaysubjectdetails.getValueAt(r, 3).toString();
        String subjectcode = displaysubjectdetails.getValueAt(r, 4).toString();
        String lhours = displaysubjectdetails.getValueAt(r, 5).toString();
        String labhours = displaysubjectdetails.getValueAt(r, 6).toString();
        String thours = displaysubjectdetails.getValueAt(r, 7).toString();
        String ehours = displaysubjectdetails.getValueAt(r, 8).toString();
        
        offeredyearbox.setSelectedItem(year);
        semesterbox.setSelectedItem(semester);
        snamebox.setText(subjectname);
        scodebox.setText(subjectcode);
        idbox.setText(id);
        lhoursbox.setValue(Integer.valueOf(lhours));
        labhoursbox.setValue(Integer.valueOf(labhours));
        thoursbox.setValue(Integer.valueOf(thours));
        ehoursbox.setValue(Integer.valueOf(ehours));
    }//GEN-LAST:event_displaysubjectdetailsMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        //If user need to enter new record , he can click this bitton
        
        
        subjectDetails s1 = new subjectDetails();
        s1.setVisible(true);
        this.dispose();
        
        
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        //for clear button
        
        offeredyearbox.setSelectedIndex(0);
        semesterbox.setSelectedIndex(0);
        snamebox.setText("");
        scodebox.setText("");
        idbox.setText("");
        lhoursbox.setValue(0);
        labhoursbox.setValue(0);
        thoursbox.setValue(0);
        ehoursbox.setValue(0);
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        //Move to previous page
        
        subjectDetails s1 = new subjectDetails();
        s1.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(displaySubjectdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(displaySubjectdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(displaySubjectdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(displaySubjectdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new displaySubjectdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable displaysubjectdetails;
    private javax.swing.JSpinner ehoursbox;
    private javax.swing.JLabel evaluationbox;
    private javax.swing.JLabel idbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labbox;
    private javax.swing.JSpinner labhoursbox;
    private javax.swing.JSpinner lhoursbox;
    private javax.swing.JComboBox<String> offeredyearbox;
    private javax.swing.JTextField scodebox;
    private javax.swing.JComboBox<String> semesterbox;
    private javax.swing.JTextField snamebox;
    private javax.swing.JSpinner thoursbox;
    private javax.swing.JLabel tutebox;
    // End of variables declaration//GEN-END:variables
}
