/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import itproject.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author User
 */
public class Parellel extends javax.swing.JInternalFrame {

    
     Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form Parellel
     */
    public Parellel() {
        initComponents();
        
        
         conn = DBconnect.connect();
    
        tableload();
    }

    
        public void  tableload()
    {
     
        try {
            
            String sql = "SELECT Day ,Subject1,Time ,Subject2 ,Duration FROM parellel";
            pst = conn.prepareStatement(sql);
           rs = pst.executeQuery(); 
           
           
           jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           
           
        } catch (Exception e) {
        }
    
    
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DayP = new javax.swing.JTextField();
        TimeP = new javax.swing.JTextField();
        Sub1P = new javax.swing.JComboBox<>();
        Sub2P = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        DurationP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Parellel Session Management");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Day");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Subject 1");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Time");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Subject 2");

        Sub1P.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cn", "OOP", "OSSA", "SPM", "ITPM", "OOC", "IWT", "IP", "PAF", " " }));
        Sub1P.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sub1PActionPerformed(evt);
            }
        });

        Sub2P.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cn", "OOP", "OSSA", "SPM", "ITPM", "OOC", "IWT", "IP", "PAF" }));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Make Parellel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Cancel");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Duration");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Day", "Subject 1", "Time", "Subject 2", "Duration"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(269, 269, 269)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DayP, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(211, 211, 211)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TimeP, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sub1P, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192)
                        .addComponent(Sub2P, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DurationP, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(183, 183, 183))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(316, 316, 316))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DayP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TimeP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DurationP, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sub2P, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sub1P, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Sub1PActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sub1PActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sub1PActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         String Day = DayP.getText();
        String Subject1 = Sub1P.getSelectedItem().toString();
        String Time = TimeP.getText();
        String Subject2 = Sub2P.getSelectedItem().toString();   
        String Duration = DurationP.getText();
        
          try {
             
        String q = "INSERT INTO parellel(Day,Subject1,Time,Subject2,Duration )values ('"+ Day  +"','"+ Subject1 +"','" + Time +"','"+ Subject2  +"','"+ Duration  +"' )";
        pst = conn.prepareStatement(q);
        pst.execute();
        } catch (SQLException e) {
            System.out.println(e);
             System.out.println("Error at add Parellel");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        
           int r = jTable1.getSelectedRow();
         
          String Day = jTable1.getValueAt(r, 0).toString();
        String Subject1 = jTable1.getValueAt(r, 1).toString();
        String Time =jTable1.getValueAt(r, 2).toString();
        String Subject2 = jTable1.getValueAt(r, 3).toString();  
        String Duration = jTable1.getValueAt(r, 4).toString();
        
           DayP.setText(Day);
         Sub1P.setSelectedItem(Subject1);
        TimeP.setText(Time);
         Sub2P.setSelectedItem(Subject2);   
       DurationP.setText(Duration);
        
      /*   
          String LecName = jTable1.getValueAt(r, 0).toString();
          String Lec2Name =  jTable1.getValueAt(r, 1).toString();
          String SubjectCode =  jTable1.getValueAt(r, 2).toString();
        String Subject =  jTable1.getValueAt(r, 3).toString();
        String Batch =  jTable1.getValueAt(r, 4).toString();
        String Tags =  jTable1.getValueAt(r, 5).toString();
        String Day =  jTable1.getValueAt(r, 6).toString();
        String Time =  jTable1.getValueAt(r, 7).toString();
        
        
        
         LName.setText(LecName);
         SubjectCS.setSelectedItem(Subject);
         TagsCS.setSelectedItem(Tags);
         DayCS.setText(Day);
         TimeCS.setText(Time);
         BatchCS.setText(Batch);
         Lname2.setText(Lec2Name);
         SubcodeCS.setSelectedItem(SubjectCode);
      
       ............................................................................................
       
          String subject1 = sub1.getSelectedItem().toString();
        String subject2 = sub2.getSelectedItem().toString();
        String subject3 = sub3.getSelectedItem().toString();
        String subject4 = sub4.getSelectedItem().toString();
        String Day1 = Day.getText();
        String Time1 = Time.getText();
        String Room1 = Room.getText();
        String Tag1 = Tag.getSelectedItem().toString();
        String Batch1 = Batch.getText();
        
        
        
          try {
             
        String q = "INSERT INTO parellel( subject1 ,subject2 , subject3 ,subject4 ,Day1 ,Time1,Room1,Tag1, Batch1 )values ('"+ Sub1  +"','"+ Sub2 +"','" +Sub3 +"','"+Sub4  +"','"+ Day +"','"+ Time  +"','"+ Room +"','"+ Tag +"','"+ Batch +"' )";
        pst = conn.prepareStatement(q);
        pst.execute();
        } catch (SQLException e) {
            System.out.println(e);
             System.out.println("Error at add Parellel");
        }
    }     
        ..................................................................................
       
                public void  tableload()
    {
     
        try {
            
            String sql = "SELECT Sub1  ,Sub2 ,Sub3  ,Sub4  ,Day ,Time,Room,Tag,Batch  FROM non_overlapping";
            pst = conn.prepareStatement(sql);
           rs = pst.executeQuery(); 
           
           
           jTable1.setModel(DbUtils.resultSetToTableModel(rs));
           
           
        } catch (Exception e) {
        }
    
    
    
    }
       
        */
      
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DayP;
    private javax.swing.JTextField DurationP;
    private javax.swing.JComboBox<String> Sub1P;
    private javax.swing.JComboBox<String> Sub2P;
    private javax.swing.JTextField TimeP;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
